#!/bin/sh
### BEGIN INIT INFO
# Provides: AlphaBrock
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Description: add run systemstart up
### END INIT INFO
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

bash /usr/local/SSR-Bash/ssadmin.sh start
